# -*- coding: utf-8 -*-
"""blueberry04_Best_optimizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ui6NoH204zQBAJjPNcD_AnEOLQx3CgOj
"""

from google.colab import drive

drive.mount('/content/gdrive')

import os

label_dirs = [
    '/content/gdrive/MyDrive/CODE/data/labels/train',
    '/content/gdrive/MyDrive/CODE/data/labels/val',
    '/content/gdrive/MyDrive/CODE/data/labels/test'
]

valid_classes = {'0', '1', '2'}  # Accept green, ripe, sobremaduro

for label_dir in label_dirs:
    if not os.path.exists(label_dir):
        continue
    for fname in os.listdir(label_dir):
        if not fname.endswith('.txt'):
            continue
        fpath = os.path.join(label_dir, fname)
        with open(fpath, 'r') as file:
            lines = file.readlines()
        new_lines = []
        for line in lines:
            parts = line.strip().split()
            if not parts or parts[0] not in valid_classes:
                continue
            if parts[0] == '2':
                parts[0] = '1'  # Merge sobremaduro into ripe
            elif parts[0] not in {'0', '1'}:
                continue
            new_lines.append(' '.join(parts) + '\n')
        with open(fpath, 'w') as file:
            file.writelines(new_lines)

print("✅ Annotations cleaned.")

!pip install ultralytics

import torch

if torch.cuda.is_available():
    print("✅ GPU is available! Using:", torch.cuda.get_device_name(0))
else:
    print("❌ GPU not available. Using CPU.")

# Step 4: Train the model
from ultralytics import YOLO

ROOT_DIR = '/content/gdrive/MyDrive/CODE'
model = YOLO("yolov8n.yaml")

results = model.train(
    data=os.path.join(ROOT_DIR, "google_colab_config.yaml"),
    epochs=100,
    optimizer="AdamW",
    save=True
)

# Step 5: Copy training results to Google Drive
!scp -r /content/runs '/content/gdrive/My Drive/CODE'

import os
from ultralytics import YOLO

# Load model
model = YOLO("yolov8n.yaml")

# Train model
results = model.train(
    data=os.path.join(ROOT_DIR, "google_colab_config.yaml"),
    epochs=100,
    optimizer="RAdam",         # 👈 pick optimizer
    #name="trainRAdam",          # 👈 custom folder name here!
    save=True,

)

!scp -r /content/runs '/content/gdrive/My Drive/CODE'

import os
from ultralytics import YOLO

# Load model
model = YOLO("yolov8n.yaml")

# Train model
results = model.train(
    data=os.path.join(ROOT_DIR, "google_colab_config.yaml"),
    epochs=100,
    optimizer="AdamW",         # 👈 pick optimizer
    #name="trainRAdam",          # 👈 custom folder name here!
    save=True,

)

!scp -r /content/runs '/content/gdrive/My Drive/CODE'