# -*- coding: utf-8 -*-
"""RipeBlueberry.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oqw-H-uBAqRKPWfUPC6ZXVVv0IgsaWSZ
"""

from google.colab import drive

drive.mount('/content/gdrive')

!pip install ultralytics

import torch

if torch.cuda.is_available():
    print("✅ GPU is available! Using:", torch.cuda.get_device_name(0))
else:
    print("❌ GPU not available. Using CPU.")

import os

# Step 4: Train the model
from ultralytics import YOLO

ROOT_DIR = '/content/gdrive/MyDrive/CODE3'
model = YOLO("yolov8n.yaml")

results = model.train(
    data=os.path.join(ROOT_DIR, "google_colab_config.yaml"),
    epochs=100,
    optimizer="SGM",
    save=True
)

# Step 5: Copy training results to Google Drive
!scp -r /content/runs '/content/gdrive/My Drive/CODE3'